// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

const fallbackDatabaseUrl =
  'postgresql://postgres:postgres@localhost_REPLACED:5432/postgres?schema=public';

export default defineConfig({
  schema: 'prisma/schema.prisma',

  migrations: {
    path: 'prisma/migrations',
    seed: 'ts-node prisma/seed.ts',
  },
  datasource: {
    url: process.env.DATABASE_URL ?? fallbackDatabaseUrl,
    // shadowDatabaseUrl: env('SHADOW_DATABASE_URL'),
  },
});
