export enum Permission {
  // Members
  MEMBER_VIEW = 'MEMBER_VIEW',
  MEMBER_CREATE = 'MEMBER_CREATE',
  MEMBER_EDIT = 'MEMBER_EDIT',

  // Memberships
  MEMBERSHIP_CREATE = 'MEMBERSHIP_CREATE',
  MEMBERSHIP_RENEW = 'MEMBERSHIP_RENEW',

  // Attendance
  ATTENDANCE_VIEW = 'ATTENDANCE_VIEW',
  ATTENDANCE_MARK = 'ATTENDANCE_MARK',

  // Staff
  STAFF_VIEW = 'STAFF_VIEW',
  STAFF_MANAGE = 'STAFF_MANAGE',

  // Dashboard
  DASHBOARD_VIEW = 'DASHBOARD_VIEW',

  // SaaS / Billing
  PLAN_UPGRADE = 'PLAN_UPGRADE',

  //Tenant
  TENANT_MANAGE = 'TENANT_MANAGE',
}
