export enum Permission {
  // Members
  MEMBER_VIEW = 'MEMBER_VIEW',
  MEMBER_CREATE = 'MEMBER_CREATE',
  MEMBER_EDIT = 'MEMBER_EDIT',

  // Memberships
  MEMBERSHIP_CREATE = 'MEMBERSHIP_CREATE',
  MEMBERSHIP_RENEW = 'MEMBERSHIP_RENEW',

  // Attendance
  ATTENDANCE_VIEW = 'ATTENDANCE_VIEW',
  ATTENDANCE_MARK = 'ATTENDANCE_MARK',

  // Staff
  STAFF_VIEW = 'STAFF_VIEW',
  STAFF_MANAGE = 'STAFF_MANAGE',

  // Dashboard
  DASHBOARD_VIEW = 'DASHBOARD_VIEW',

  // SaaS / Billing
  PLAN_UPGRADE = 'PLAN_UPGRADE',

  // Tenant
  TENANT_MANAGE = 'TENANT_MANAGE',

  // Mobibix Core Module Permissions
  INVENTORY_VIEW = 'INVENTORY_VIEW',
  INVENTORY_MANAGE = 'INVENTORY_MANAGE',
  SALES_VIEW = 'SALES_VIEW',
  SALES_CREATE = 'SALES_CREATE',
  SALES_CANCEL = 'SALES_CANCEL',
  REPAIR_MANAGE = 'REPAIR_MANAGE',
  SHOP_MANAGE = 'SHOP_MANAGE',
}
