export enum WhatsAppFeature {
  // Global Plan Features
  MEMBERS_MANAGEMENT = 'MEMBERS_MANAGEMENT',
  ATTENDANCE_MANAGEMENT = 'ATTENDANCE_MANAGEMENT',
  STAFF_MANAGEMENT = 'STAFF_MANAGEMENT',
  QR_ATTENDANCE = 'QR_ATTENDANCE',
  REPORTS = 'REPORTS',
  MEMBER_PAYMENT_TRACKING = 'MEMBER_PAYMENT_TRACKING',

  // WhatsApp Specific
  WHATSAPP_ALERTS_BASIC = 'WHATSAPP_ALERTS_BASIC',
  WHATSAPP_ALERTS_ALL = 'WHATSAPP_ALERTS_ALL',

  // Legacy / Specific
  WELCOME = 'WELCOME',
  EXPIRY = 'EXPIRY',
  PAYMENT_DUE = 'PAYMENT_DUE',
  REMINDER = 'REMINDER',
}
