-- SYNC PROD SCHEMA (Empty on Local Dev because it conflicts with dev_initialize)
-- This migration was likely generated to fix a production environment but is redundant here.
-- Leaving empty to fix shadow database sync.
