// Timeline activity source types
export enum TimelineSource {
  INVOICE = 'INVOICE',
  JOB = 'JOB',
  RECEIPT = 'RECEIPT',
  QUOTATION = 'QUOTATION',
  FOLLOW_UP = 'FOLLOW_UP',
  REMINDER = 'REMINDER',
  WHATSAPP = 'WHATSAPP',
  LOYALTY = 'LOYALTY',
  ALERT = 'ALERT',
  SYSTEM = 'SYSTEM',
}

// Timeline activity type (granular)
export enum TimelineActivityType {
  // Invoice
  INVOICE_CREATED = 'INVOICE_CREATED',
  INVOICE_PAID = 'INVOICE_PAID',
  INVOICE_CREDIT = 'INVOICE_CREDIT',

  // Job Card
  JOB_CREATED = 'JOB_CREATED',
  JOB_STATUS_CHANGED = 'JOB_STATUS_CHANGED',
  JOB_DELIVERED = 'JOB_DELIVERED',

  // Receipt / Payment
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  RECEIPT_CREATED = 'RECEIPT_CREATED',

  // Quotation
  QUOTATION_CREATED = 'QUOTATION_CREATED',
  QUOTATION_SENT = 'QUOTATION_SENT',
  QUOTATION_ACCEPTED = 'QUOTATION_ACCEPTED',

  // Follow-Up (CRM)
  FOLLOWUP_CREATED = 'FOLLOWUP_CREATED',
  FOLLOWUP_COMPLETED = 'FOLLOWUP_COMPLETED',
  FOLLOWUP_CANCELLED = 'FOLLOWUP_CANCELLED',

  // Reminder
  REMINDER_SENT = 'REMINDER_SENT',
  REMINDER_FAILED = 'REMINDER_FAILED',

  // WhatsApp
  WHATSAPP_SENT = 'WHATSAPP_SENT',
  WHATSAPP_FAILED = 'WHATSAPP_FAILED',
  WHATSAPP_DELIVERED = 'WHATSAPP_DELIVERED',

  // Loyalty
  LOYALTY_EARNED = 'LOYALTY_EARNED',
  LOYALTY_REDEEMED = 'LOYALTY_REDEEMED',

  // Alert
  ALERT_CREATED = 'ALERT_CREATED',
  ALERT_RESOLVED = 'ALERT_RESOLVED',

  // System
  CUSTOMER_CREATED = 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED = 'CUSTOMER_UPDATED',
}
